name: Run FastAPI Tests

on:
  push:
    branches:
      - 'main'
      - 'développement'
      - 'feature/**'
      - main

  pull_request:
    branches:
      - 'main'
      - 'développement'
      - 'feature/**'
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
          TESTING: true
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for DB to be ready..."
          sleep 10  # ou utilise psycopg2 pour vérifier activement la connexion

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
        run: |
          pytest tests/
