name: CI Pipeline - client-api

on:
  push:
    branches:
      - 'main'
      - 'développement'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'développement'
      - 'feature/**'

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          pip install black flake8

      - name: Run black
        run: black . --check .

#      - name: Run flake8
#        run: flake8 .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_TOKEN: ${{secrets.API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run pytest with coverage
        run: pytest --cov=app --cov-report=term-missing
